export const language_names = [
  "Default",
  "English(American)",
  "English(British)",
  "English(Canadian)",
  "English(Indian)",
  "English(Scottish)",
  "English(Irish)",
  "English(Australian)",
  "English(New Zealand)",
  "English(Singapore)",
  "Afrikaans",
  "Shqip (Albanian)",
  "العربية (Arabic)",
  "Հայերեն (Armenian)",
  "অসমীয়া (Assamese)",
  "Azərbaycan dili (Azerbaijani)",
  "Euskara (Basque)",
  "Беларуская мова (Belarusian)",
  "বাংলা (Bengali)",
  "Bosanski jezik (Bosnian)",
  "Български език (Bulgarian)",
  "ဗမာစာ (Burmese)",
  "Català (Catalan)",
  "简体中文 (Chinese Simplified)",
  "繁體中文 (Chinese Traditional)",
  "Hrvatski jezik (Croatian)",
  "Čeština (Czech)",
  "Dansk (Danish)",
  "Nederlands (Dutch)",
  "Esperanto",
  "Eesti keel (Estonian)",
  "Wikang Filipino (Tagalog)",
  "Suomi (Finnish)",
  "Français (French)",
  "Galego (Galician)",
  "ქართული (Georgian)",
  "Deutsch (German)",
  "Ελληνικά (Greek)",
  "ગુજરાતી (Gujarati)",
  "Kreyòl Ayisyen (Haitian Creole)",
  "هَوُسَ (Hausa)",
  "עִבְרִית (Hebrew)",
  "हिन्दी (Hindi)",
  "Hmoob (Hmong)",
  "Magyar (Hungarian)",
  "Íslenska (Icelandic)",
  "Asụsụ Igbo (Igbo)",
  "Bahasa Indonesia (Indonesian)",
  "Gaeilge (Irish)",
  "Italiano (Italian)",
  "日本語 (Japanese)",
  "Basa Jawa (Javanese)",
  "ಕನ್ನಡ (Kannada)",
  "Қазақ тілі (Kazakh)",
  "ភាសាខ្មែរ (Khmer)",
  "Ikinyarwanda (Kinyarwanda)",
  "한국어 (Korean)",
  "کوردی (Sorani)",
  "Кыргыз тили (Kyrgyz)",
  "ພາສາລາວ (Lao)",
  "Latviešu valoda (Latvian)",
  "Lietuvių kalba (Lithuanian)",
  "Lëtzebuergesch (Luxembourgish)",
  "Македонски јазик (Macedonian)",
  "Malagasy fiteny (Malagasy)",
  "Bahasa Melayu (Malay)",
  "മലയാളം (Malayalam)",
  "Malti (Maltese)",
  "Te Reo Māori (Maori)",
  "मराठी (Marathi)",
  "Монгол хэл (Mongolian)",
  "नेपाली (Nepali)",
  "Norsk (Norwegian)",
  "ଓଡ଼ିଆ (Oriya)",
  "Afaan Oromoo (Oromo)",
  "پښتو (Pashto)",
  "فارس (Farsi)",
  "Polski (Polish)",
  "Português (Portuguese)",
  "ਪੰਜਾਬੀ (Punjabi)",
  "Română (Romanian)",
  "Русский (Russian)",
  "Gagana Samoa (Samoan)",
  "Gàidhlig (Scots Gaelic)",
  "Српски језик (Serbian)",
  "Sesotho (Sesotho)",
  "chiShona (Shona)",
  "سنڌي (Sindhi)",
  "සිංහල (Sinhala)",
  "Slovenčina (Slovak)",
  "Slovenščina (Slovenian)",
  "Af-Soomaali (Somali)",
  "Español (Spanish)",
  "Basa Sunda (Sundanese)",
  "Kiswahili (Swahili)",
  "Svenska (Swedish)",
  "Тоҷикӣ (Tajik)",
  "தமிழ் (Tamil)",
  "Татар теле (Tatar)",
  "తెలుగు (Telugu)",
  "ภาษาไทย (Thai)",
  "ትግርኛ (Tigrinya)",
  "lea fakatonga (Tongan)",
  "Türkçe (Turkish)",
  "Türkmençe (Turkmen)",
  "Українська (Ukrainian)",
  "اردو (Urdu)",
  "Oʻzbek tili (Uzbek)",
  "Tiếng Việt (Vietnamese)",
  "Cymraeg (Welsh)",
  "Wolof (Wolof)",
  "isiXhosa (Xhosa)",
  "ייִדיש (Yiddish)",
  "Èdè Yorùbá (Yoruba)",
  "isiZulu (Zulu)"
]

export const formats = [
  "FAQ",
  "Listicle",
  "Interview",
  "Review",
  "News",
  "Opinion",
  "Tutorial",
  "Case Study",
  "Profile",
  "Blog",
  "Poem",
  "Script",
  "Whitepaper",
  "eBook",
  "Press Release",
  "Infographic",
  "Webinar",
  "Podcast Script",
  "Email Campaign",
  "Social Media Post",
  "Proposal",
  "Brochure",
  "Newsletter",
  "Presentation",
  "Product Description",
  "Research Paper",
  "Speech",
  "Memo",
  "Policy Document",
  "User Guide",
  "Technical Documentation",
  "Q&A"
]

export const styles = [
  "Authoritative",
  "Clinical",
  "Cold",
  "Confident",
  "Cynical",
  "Emotional",
  "Empathetic",
  "Formal",
  "Friendly",
  "Humorous",
  "Informal",
  "Ironic",
  "Optimistic",
  "Pessimistic",
  "Playful",
  "Sarcastic",
  "Serious",
  "Sympathetic",
  "Tentative",
  "Warm"
]

export const tones = [
  "Authoritative",
  "Clinical",
  "Cold",
  "Confident",
  "Cynical",
  "Emotional",
  "Empathetic",
  "Formal",
  "Friendly",
  "Humorous",
  "Informal",
  "Ironic",
  "Optimistic",
  "Pessimistic",
  "Playful",
  "Sarcastic",
  "Serious",
  "Sympathetic",
  "Tentative",
  "Warm"
]

export const response_lengths = [
  "50 words",
  "100 words",
  "250 words",
  "500 words",
  "1000 words",
  "1500 words",
  "2000 words",
  "2500 words",
  "3000 words"
]